### ISSUE TITLE
one question~

### ISSUE THREAD

**Issue by jianshuowang** [albeco/LaserPulse#4]
hello，Why is the envelope of spectralIntensity and spectrum different？I think they're just different on the horizontal axis

**Comment by jianshuowang** [comment]
plot(p2.wavelengthArray, real(p2.spectrum));
hold on；
plot(p2.wavelengthArray,real(p2.spectralIntensity));

**Comment by jianshuowang** [comment]
1

**Comment by albeco** [comment]
Hi Jianshu,

the reason is that the spectral intensity is meant to be plotted vs frequency, while the spectrum is meant to be plotted vs the wavelength. The normalization therefore is different 

spectral_intensity(frequency) == spectrum(lambda) * lambda^2 / c

(see e.g. https://www.rp-photonics.com/spectral_quantities.html)

**Comment by jianshuowang** [comment]
- Thank you very much. ^^
